Add error handlers to hooks and scripts

diff --git a/openssh-initramfs/usr/share/initramfs-tools/scripts/init-premount/start-openssh b/openssh-initramfs/usr/share/initramfs-tools/scripts/init-premount/start-openssh
--- a/openssh-initramfs/usr/share/initramfs-tools/scripts/init-premount/start-openssh
+++ b/openssh-initramfs/usr/share/initramfs-tools/scripts/init-premount/start-openssh
@@ -1,5 +1,6 @@
 #!/bin/sh
 set -e
+set -o pipefail
 
 PREREQ=""
 
@@ -16,6 +17,12 @@ prereqs)
     exit 0
     ;;
 esac
+
+error_func() {
+    echo "start-openssh script failed"
+    panic
+}
+trap error_func ERR
 
 . /scripts/functions
 . /scripts/openssh.conf
diff --git a/wifi-initramfs/usr/share/initramfs-tools/scripts/init-premount/enable-wireless b/wifi-initramfs/usr/share/initramfs-tools/scripts/init-premount/enable-wireless
--- a/wifi-initramfs/usr/share/initramfs-tools/scripts/init-premount/enable-wireless
+++ b/wifi-initramfs/usr/share/initramfs-tools/scripts/init-premount/enable-wireless
@@ -1,5 +1,6 @@
 #!/bin/sh
 set -e
+set -o pipefail
 
 PREREQ=""
 prereqs() {
@@ -11,6 +12,12 @@ prereqs)
     exit 0
     ;;
 esac
+
+error_func() {
+    echo "enable-wireless script failed"
+    panic
+}
+trap error_func ERR
 
 . /scripts/functions
 . /scripts/wireless.conf
