Add error handlers to hooks and scripts

diff --git a/openssh-initramfs/usr/share/initramfs-tools/hooks/openssh b/openssh-initramfs/usr/share/initramfs-tools/hooks/openssh
--- a/openssh-initramfs/usr/share/initramfs-tools/hooks/openssh
+++ b/openssh-initramfs/usr/share/initramfs-tools/hooks/openssh
@@ -1,5 +1,6 @@
 #!/bin/sh
 set -e
+set -o pipefail
 
 PREREQ="cryptroot cryptroot-unlock"
 
@@ -16,6 +17,12 @@ prereqs)
     exit 0
     ;;
 esac
+
+error_func() {
+    echo "openssh hook failed"
+    exit 1
+}
+trap error_func ERR
 
 . /usr/share/initramfs-tools/hook-functions
 
diff --git a/openssh-initramfs/usr/share/initramfs-tools/scripts/local-bottom/stop-openssh b/openssh-initramfs/usr/share/initramfs-tools/scripts/local-bottom/stop-openssh
--- a/openssh-initramfs/usr/share/initramfs-tools/scripts/local-bottom/stop-openssh
+++ b/openssh-initramfs/usr/share/initramfs-tools/scripts/local-bottom/stop-openssh
@@ -1,5 +1,6 @@
 #!/bin/sh
 set -e
+set -o pipefail
 
 PREREQ=""
 prereqs() {
@@ -12,14 +13,22 @@ prereqs)
     ;;
 esac
 
+error_func() {
+    echo "stop-openssh script failed"
+    sleep 3
+}
+trap error_func ERR
+
 . /scripts/functions
 . /scripts/openssh.conf
 
 if grep -qw "openssh" /proc/cmdline; then
-    echo "Killing OpenSSH"
-    kill $(cat /run/initram-openssh.pid)
+    if [ -f /run/initramfs-openssh.pid ]; then
+        echo "Killing OpenSSH"
+        kill $(cat /run/initram-openssh.pid)
 
-    rm -f /run/initram-openssh.pid
+        rm -f /run/initram-openssh.pid
 
-    echo "Killed OpenSSH"
+        echo "Killed OpenSSH"
+    fi
 fi
diff --git a/wifi-initramfs/usr/share/initramfs-tools/hooks/wireless b/wifi-initramfs/usr/share/initramfs-tools/hooks/wireless
--- a/wifi-initramfs/usr/share/initramfs-tools/hooks/wireless
+++ b/wifi-initramfs/usr/share/initramfs-tools/hooks/wireless
@@ -1,5 +1,6 @@
 #!/bin/sh
 set -e
+set -o pipefail
 
 PREREQ=""
 prereqs() {
@@ -11,6 +12,12 @@ prereqs)
     exit 0
     ;;
 esac
+
+error_func() {
+    echo "wireless hook failed"
+    exit 1
+}
+trap error_func ERR
 
 . /usr/share/initramfs-tools/hook-functions
 
diff --git a/wifi-initramfs/usr/share/initramfs-tools/scripts/local-bottom/kill-wireless b/wifi-initramfs/usr/share/initramfs-tools/scripts/local-bottom/kill-wireless
--- a/wifi-initramfs/usr/share/initramfs-tools/scripts/local-bottom/kill-wireless
+++ b/wifi-initramfs/usr/share/initramfs-tools/scripts/local-bottom/kill-wireless
@@ -1,5 +1,6 @@
 #!/bin/sh
 set -e
+set -o pipefail
 
 PREREQ=""
 
@@ -16,6 +17,12 @@ prereqs)
     exit 0
     ;;
 esac
+
+error_func() {
+    echo "kill-wireless script failed"
+    sleep 3
+}
+trap error_func ERR
 
 . /scripts/functions
 . /scripts/wireless.conf
